version: 1
validation: sovereign
default_denom: udrc
genesis:
  chain_id: "divine"
  app_state:
    staking:
      params:
        bond_denom: "uDRC"
        unbonding_time: "1814400s"
    # The bank module also has a default base denom
    bank:
      denom_metadata:
        - name: "Divine Ray Token"
          base: "uDRC"
          symbol: "DRC"
          display: "DRC"
          description: "The native staking token of the Divine chain."
          denom_units:
            - denom: "uDRC"
              exponent: 0
              aliases: ["microDRC"]
            - denom: "DRC"
              exponent: 6
accounts: 
- name: divine-validator-1
  coins:
  - 150000000000000000uDRC
- name: divine-validator-2
  coins:
  - 150000000000000000uDRC
- name: divine-validator-3
  coins:
  - 150000000000000000uDRC
- name: divine-ico-wallet
  coins:
  - 1500000000000000000uDRC
- name: faucet-account
  coins:
  - 50000000000000000uDRC
- name: management-account
  coins:
  - 3000000000000000000uDRC
client:
  openapi:
    path: docs/static/openapi.json
faucet:
  name: faucet-account
  coins:
  - 5000000uDRC
  coins_max:
  - 100000000uDRC
  port: 4500
  rate_limit_window: 3600s
validators:
- name: divine-validator-1
  bonded: 150000000000000000uDRC
  home: "/Users/kaustavchakraborty/Projects/DivineRay/blockchain/config/test/validator1"
  app:
    minimum-commission-rate: "0.05"
    minimum-gas-prices: "0.0025DRC"
    pruning: "nothing"
  config:
    moniker: "divine-validator-1"
  client:
      output: "json"
  gentx:
    moniker: "divine-validator-1"
    keyring-backend: "os"
    chain-id: "divine"
    keyring-dir: "/Users/kaustavchakraborty/Projects/DivineRay/blockchain/config/test/keys"
# - name: divine-validator-2
#   bonded: 150000000000000000uDRC
#   app:
#     minimum-commission-rate: "0.05"
#     minimum-gas-prices: "0.0025DRC"
# - name: divine-validator-3
#   bonded: 150000000000000000uDRC
#   app:
#     minimum-commission-rate: "0.05"
#     minimum-gas-prices: "0.0025DRC"